//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoursForRequest
    {
        public int id { get; set; }
        public Nullable<int> requestId { get; set; }
        public Nullable<System.TimeSpan> fromUTCHour { get; set; }
        public Nullable<System.TimeSpan> toUTCHour { get; set; }
        public Nullable<int> weekDay { get; set; }
    
        public virtual RequestParameter RequestParameter { get; set; }
    }
}
