//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int partnerId { get; set; }
        public Nullable<int> req1 { get; set; }
        public Nullable<int> req2 { get; set; }
        public Nullable<int> statusId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual RequestParameter RequestParameter { get; set; }
        public virtual RequestParameter RequestParameter1 { get; set; }
    }
}
