//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestParameter()
        {
            this.hoursForRequests = new HashSet<hoursForRequest>();
            this.Partners = new HashSet<Partner>();
            this.Partners1 = new HashSet<Partner>();
        }
    
        public int requestId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<bool> wayLearn { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> subCategoryId { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<bool> kindLearn { get; set; }
        public Nullable<bool> found { get; set; }
        public Nullable<bool> cancel { get; set; }
        public string alertTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoursForRequest> hoursForRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner> Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner> Partners1 { get; set; }
        public virtual User User { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
